name: 'Godot Export'
description: 'Automatically exports your Godot games.'
author: 'Firebelley'
branding:
  icon: 'box'
  color: 'white'
inputs:
  base_version:
    description: Base version. Patch versions are incremented when this action runs.
    default: 0.0.1
    required: false
  godot_executable_download_url:
    description: The download url of the 64 bit Linux Headless Godot executable
    required: true
  godot_export_templates_download_url:
    description: The url of the export templates corresponding to the Godot executable version
    required: true
  relative_project_path:
    description: The relative path containing the "project.godot" file
    required: true
  create_release:
    description: Should a release be created.
    default: true
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
